[tool.poetry]
name = "ansible-role-zfs"
version = "0.0.0"
description = "Ansible Role for ZFS"
authors = ["Remerge GmbH <core@remerge.io>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10, < 3.13"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
flake8 = "^7.1.1"
flake8-bugbear = "^24.8.19"
pylint = "^3.2.6"
ansible-lint = { version = "^24.7.0", markers = "platform_system != 'Windows'" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
